import type { Language } from '@/types';

type Dict = Record<string, { id: string; en: string }>;

const STRINGS: Dict = {
  play: { id: 'Main', en: 'Play' },
  home: { id: 'Beranda', en: 'Home' },
  leaderboard: { id: 'Papan Skor', en: 'Leaderboard' },
  stats: { id: 'Statistik', en: 'Stats' },
  settings: { id: 'Pengaturan', en: 'Settings' },
  score: { id: 'Skor', en: 'Score' },
  streak: { id: 'Beruntun', en: 'Streak' },
  time: { id: 'Waktu', en: 'Time' },
  level: { id: 'Level', en: 'Level' },
  gameOver: { id: 'Permainan Selesai', en: 'Game Over' },
  playAgain: { id: 'Main Lagi', en: 'Play Again' },
  backHome: { id: 'Ke Beranda', en: 'Back Home' },
  difficulty: { id: 'Kesulitan', en: 'Difficulty' },
  easy: { id: 'Mudah', en: 'Easy' },
  medium: { id: 'Sedang', en: 'Medium' },
  hard: { id: 'Sulit', en: 'Hard' },
  language: { id: 'Bahasa', en: 'Language' },
  start: { id: 'Mulai', en: 'Start' },
  correct: { id: 'Benar', en: 'Correct' },
  wrong: { id: 'Salah', en: 'Wrong' },
  newBest: { id: 'Rekor Baru!', en: 'New Best!' },
  goPremium: { id: 'Jadi Premium', en: 'Go Premium' },
  premiumActive: { id: 'Premium Aktif', en: 'Premium Active' },
  noAds: { id: 'Tanpa Iklan', en: 'No Ads' },
  guest: { id: 'Tamu', en: 'Guest' },
  login: { id: 'Masuk', en: 'Login' },
  register: { id: 'Daftar', en: 'Register' },
  logout: { id: 'Keluar', en: 'Logout' },
  email: { id: 'Email', en: 'Email' },
  password: { id: 'Kata Sandi', en: 'Password' },
  username: { id: 'Nama Pengguna', en: 'Username' },
  playAsGuest: { id: 'Main sebagai Tamu', en: 'Play as Guest' },
  found: { id: 'Ditemukan', en: 'Found' },
  wordsLeft: { id: 'Kata tersisa', en: 'Words left' },
  flips: { id: 'Balikan', en: 'Flips' },
  pairs: { id: 'Pasangan', en: 'Pairs' },
  across: { id: 'Mendatar', en: 'Across' },
  down: { id: 'Menurun', en: 'Down' },
  check: { id: 'Periksa', en: 'Check' },
  tapToStart: { id: 'Ketuk untuk mulai', en: 'Tap to start' },
  trueLabel: { id: 'BENAR', en: 'TRUE' },
  falseLabel: { id: 'SALAH', en: 'FALSE' },
  tapInOrder: { id: 'Ketuk angka 1 ke atas secepatnya!', en: 'Tap numbers from 1 upward, fast!' },
  trueFalseHint: { id: 'Benar atau salah? 60 detik!', en: 'True or false? 60 seconds!' },
  best: { id: 'Terbaik', en: 'Best' },
  findOdd: { id: 'Mana yang berbeda?', en: 'Which one is different?' },
  watchPattern: { id: 'Lihat polanya...', en: 'Watch the pattern...' },
  repeatPattern: { id: 'Ulangi polanya!', en: 'Repeat the pattern!' },
  arrangeTiles: { id: 'Susun angka 1 ke atas, kotak kosong di akhir', en: 'Arrange tiles in order, blank last' },
  moves: { id: 'Langkah', en: 'Moves' },
  round: { id: 'Ronde', en: 'Round' },
  solved: { id: 'Selesai!', en: 'Solved!' },
  watch: { id: 'LIHAT', en: 'WATCH' },
  yourTurn: { id: 'GILIRANMU', en: 'YOUR TURN' },
  hello: { id: 'Halo', en: 'Hi' },
  trainBrain: { id: 'Asah otakmu hari ini.', en: 'Train your brain today.' },
  buyPremiumCta: { id: '💎 BELI PREMIUM · TANPA IKLAN $10 →', en: '💎 GO PREMIUM · NO ADS $10 →' },
  orSignInWith: { id: 'Atau masuk dengan', en: 'Or sign in with' },
  numbers: { id: 'angka', en: 'numbers' },
  mathReady: { id: '60 detik. Sebanyak mungkin jawaban benar!', en: '60 seconds. Solve as many as you can!' },
  wordsSolved: { id: 'kata benar', en: 'words solved' },
  typeContinuously: { id: 'Ketik berurutan, kotak pindah otomatis.', en: 'Type continuously; cells auto-advance.' },
  share: { id: 'BAGIKAN', en: 'SHARE' },
  shareResultBtn: { id: '📤 BAGIKAN HASIL', en: '📤 SHARE RESULT' },
  offlineBoard: { id: 'Mode offline — login & online untuk papan skor global.', en: 'Offline — login & go online for the global board.' },
  noScores: { id: 'Belum ada skor. Jadilah yang pertama!', en: 'No scores yet. Be the first!' },
  loading: { id: 'Memuat…', en: 'Loading…' },
  games: { id: 'Main', en: 'Games' },
  totalScore: { id: 'Total Skor', en: 'Total' },
  played: { id: 'Dimainkan', en: 'Played' },
  loginFirst: { id: 'Login dulu untuk membeli premium.', en: 'Please login first.' },
  restorePurchase: { id: 'Pulihkan Pembelian', en: 'Restore Purchase' },
  exit: { id: 'Keluar', en: 'Exit' },
  tagline: { id: 'Latihan Otak 5-in-1', en: '5-in-1 Brain Training' },
  tapToPlay: { id: 'Ketuk PLAY untuk mulai', en: 'Tap PLAY to start' },
  premiumDesc: { id: '$10 sekali bayar — tanpa iklan selamanya, unlock semua tema & kartu.', en: '$10 one-time — no ads forever, unlock all themes & card sets.' },
  shareLeaderboard: {
    id: '🏆 Aku lagi naik di papan skor NarVara BrainGame! Ayo lawan aku 🔥 https://play.google.com/store/apps/details?id=com.narvara.braingame',
    en: "🏆 I'm climbing the NarVara BrainGame leaderboard! Come challenge me 🔥 https://play.google.com/store/apps/details?id=com.narvara.braingame",
  },
};

export function t(key: keyof typeof STRINGS, lang: Language): string {
  return STRINGS[key]?.[lang] ?? key;
}

export function createTranslator(lang: Language) {
  return (key: keyof typeof STRINGS) => t(key, lang);
}
